//! `.claude/commands/accept.md`, `revise.md`, `handover.md`: the decisions
//! a user types to Claude Code. zforge's prompt hook records them before
//! the model sees the message (`crate::hook`); these files make the
//! commands known to Claude Code (listed, completed) and tell the model
//! what to do once the hook has answered.
//!
//! A file is written when missing and refreshed while it carries
//! [`MARKER`]; one the project wrote under the same name is left alone.

use anyhow::Result;
use std::path::Path;

pub(crate) const MARKER: &str = "<!-- generated by zforge";

const COMMANDS: [(&str, &str); 3] = [
    (
        "accept.md",
        include_str!("../../../templates/commands/accept.md"),
    ),
    (
        "revise.md",
        include_str!("../../../templates/commands/revise.md"),
    ),
    (
        "handover.md",
        include_str!("../../../templates/commands/handover.md"),
    ),
];

#[derive(Debug, Default, PartialEq, Eq)]
pub(crate) struct Written {
    pub written: usize,
    /// Files of the project's own, left as they are.
    pub theirs: Vec<String>,
}

pub(crate) fn write(project_root: &Path) -> Result<Written> {
    let dir = project_root.join(".claude").join("commands");
    std::fs::create_dir_all(&dir)?;
    let mut out = Written::default();
    for (name, body) in COMMANDS {
        let path = dir.join(name);
        match std::fs::read_to_string(&path) {
            Ok(current) if current == body => {}
            Ok(current) if !current.contains(MARKER) => out.theirs.push(name.to_string()),
            _ => {
                crate::fs::write_atomic(&path, body.as_bytes())?;
                out.written += 1;
            }
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn written_then_refreshed_and_the_projects_own_kept() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join(".claude/commands");

        assert_eq!(write(tmp.path()).unwrap().written, 3);
        let accept = std::fs::read_to_string(dir.join("accept.md")).unwrap();
        assert!(accept.contains("$ARGUMENTS") && accept.contains(MARKER));

        // An older generated copy is refreshed; the project's own is kept.
        std::fs::write(dir.join("revise.md"), format!("{MARKER} -->\nold\n")).unwrap();
        std::fs::write(dir.join("handover.md"), "# ours\n").unwrap();
        let again = write(tmp.path()).unwrap();
        assert_eq!(again.written, 1);
        assert_eq!(again.theirs, ["handover.md"]);
        assert_eq!(
            std::fs::read_to_string(dir.join("handover.md")).unwrap(),
            "# ours\n"
        );
        assert_eq!(write(tmp.path()).unwrap().written, 0);
    }

    /// Every command the hook understands has a file, and every file
    /// forbids the model from recording the decision itself.
    #[test]
    fn each_command_file_matches_the_hook() {
        for (name, body) in COMMANDS {
            let cmd = format!("/{} x", name.trim_end_matches(".md"));
            assert!(
                crate::hook::command::parse(&cmd).is_some(),
                "{name} is not a hook command"
            );
            assert!(body.contains("You did not record it"), "{name}");
            assert!(body.contains("zforge init --force"), "{name}");
        }
    }
}
